services:
  db:
    image: ankane/pgvector  # PostgreSQL with pgvector support
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vector_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  fastapi-app:
    build: .
    container_name: fastapi-container
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PGVECTOR_HOST: db
      PGVECTOR_PORT: 5432
      PGVECTOR_DB: vector_db
      PGVECTOR_USER: user
      PGVECTOR_PASSWORD: password
      SCRAPER_USER_AGENT: ScrapperBot/1.0
    volumes:
      - .:/app

volumes:
  pgvector_data:
